rendering:
  enabled: true
  fps: 30

simulation:
  timestep: 0.001
  control_frequency: 1000
  model_path: "../models/mujoco/scenes/world_scene.xml"

devices:
  - name: arm_left
    model_path: "../models/mujoco/robots/franka_fr3/fr3_torque.xml"
    urdf_path: "../models/urdf/franka_fr3/fr3_franka_hand.urdf"
    root_body: "link0"
    urdf_ee_name: "fr3_hand"
    gripper_actuator: "actuator8"
  
  - name: hand_left
    model_path: "../models/mujoco/robots/franka_fr3/hand.xml"
    root_body: "hand"
    gripper_actuator: "actuator8"
    attach_to: "arm_left_fr3_link7"
    attach_offset:
      position: [0, 0, 0.107]
      orientation: [0.9239, 0, 0, -0.3827]

  - name: arm_right
    model_path: "../models/mujoco/robots/franka_fr3/fr3_torque.xml"
    urdf_path: "../models/urdf/franka_fr3/fr3_franka_hand.urdf"
    root_body: "link0"
    urdf_ee_name: "fr3_hand"
    gripper_actuator: "actuator8"

  - name: hand_right
    model_path: "../models/mujoco/robots/franka_fr3/hand.xml"
    root_body: "hand"
    gripper_actuator: "actuator8"
    attach_to: "arm_right_fr3_link7"
    attach_offset:
      position: [0, 0, 0.107]
      orientation: [0.9239, 0, 0, -0.3827]

  - name: head
    model_path: "../models/mujoco/robots/pan_tilt_dummy/pan_tilt_dummy.xml"
    root_body: "base"

objects:
  - name: table
    type: static
    model_path: "../models/mujoco/props/table.xml"
    pose:
      position: [0.4, 0, 0]
      orientation: [1, 0, 0, 0]

  - name: wall
    type: static
    model_path: "../models/mujoco/props/wall.xml"
    pose:
      position: [0, 0, 0]
      orientation: [1, 0, 0, 0]

  - name: right_base_frame
    type: visual
    model_path: "../models/mujoco/props/coordinate_frame.xml"
    pose:
      position: [0, -0.6, 0.8]
      orientation: [0.5, 0.5, 0.5, 0.5]

  - name: box_1
    type: dynamic
    model_path: "../models/mujoco/props/box_red.xml"
    pose:
      position: [0.8, 0.0, 0.6]
      orientation: [1, 0, 0, 0]

  #- name: box_2
  #  type: dynamic
  #  model_path: "../models/mujoco/props/box_green.xml"
  #  pose:
  #    position: [0.8, 0.3, 0.6]
  #    orientation: [1, 0, 0, 0]

  #- name: box_3
  #  type: dynamic
  #  model_path: "../models/mujoco/props/box_blue.xml"
  #  pose:
  #    position: [0.8, -0.3, 0.6]
  #    orientation: [1, 0, 0, 0]

  - name: target_right
    type: mocap
    model_path: "../models/mujoco/props/target_frame.xml"
    enabled: True
    pose:
      position: [0, 0, 0]
      orientation: [1, 0, 0, 0]

  - name: target_left
    type: mocap
    model_path: "../models/mujoco/props/target_frame.xml"
    enabled: True
    pose:
      position: [0, 0, 0]
      orientation: [1, 0, 0, 0]

  - name: place_pose
    type: mocap
    model_path: "../models/mujoco/props/target_frame.xml"
    enabled: True
    pose:
      position: [0, 0, 0]
      orientation: [1, 0, 0, 0]





cameras:
  - name: workspace_overview_1
    enabled: False
    type: fixed
    pos: [1.5, 0, 0.8]
    look_at: [0.4, 0.0, 0.4]
    fovy: 90

  - name: workspace_overview_2
    enabled: False
    type: fixed
    pos: [0.3, 0.3, 1.9]
    look_at: [0.0, 0.0, 0.4]
    fovy: 90

  - name: workspace_overview_3
    enabled: False
    type: fixed
    pos: [0.5, 0.3, 0.9]
    look_at: [0.5, 0.0, 0.7]
    fovy: 90